=== githubjvy/SamplesAndDemo/jvy-deloitte-exam/jy-deloitte-exam-db-sys-api/src/main/resources/api/schemas/get-users-response-success-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "count": {
      "type": "integer"
    },
    "pageNumber": {
      "type": "integer"
    },
    "pageSize": {
      "type": "integer"
    },
    "users": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "username": {
              "type": "string"
            },
            "fullName": {
              "type": "string"
            },
            "birthday": {
              "type": "string"
            },
            "gender": {
              "type": "string"
            },
            "dateRegistered": {
              "type": "string"
            }
          },
          "required": [
            "username",
            "fullName",
            "birthday",
            "gender",
            "dateRegistered"
          ]
        },
        {
          "type": "object",
          "properties": {
            "username": {
              "type": "string"
            },
            "fullName": {
              "type": "string"
            },
            "birthday": {
              "type": "string"
            },
            "gender": {
              "type": "string"
            },
            "dateRegistered": {
              "type": "string"
            },
            "isActive": {
              "type": "boolean"
            }
          },
          "required": [
            "username",
            "fullName",
            "birthday",
            "gender",
            "isActive",
            "dateRegistered"
          ]
        }
      ]
    }
  },
  "required": [
    "count",
    "pageNumber",
    "pageSize",
    "users"
  ]
}

=== githubjvy/SamplesAndDemo/jvy-deloitte-exam/jy-deloitte-exam-proc-api/src/main/resources/api/examples/get-users-response-success-example.json
{
   "count":2,
   "pageNumber":1,
   "pageSize":10,
   "users":[
      {
         "username":"user1",
         "fullname":"Jerome Yabut",
         "age":13,
         "gender":"male",
         "dateRegistered":"20-08-2012"
      },
      {
         "username":"user2",
         "fullname":"JY Yabut",
         "age":13,
         "gender":"male",
         "dateRegistered":"21-08-2012"
      }
   ]
}

=== githubjvy/SamplesAndDemo/jvy-deloitte-exam/jy-deloitte-exam-db-sys-api/src/main/resources/api/examples/get-users-response-success-example.json
{
   "count":2,
   "pageNumber":1,
   "pageSize":10,
   "users":[
      {
         "username":"user1",
         "fullName":"Jerome Yabut",
         "birthday":"01-01-1990",
         "gender":"male",
         "isActive" : true,
         "dateRegistered":"20-08-2012"
      },
      {
         "username":"user2",
         "fullName":"JY Yabut",
         "birthday":"01-02-1990",
         "gender":"male",
         "isActive" : true,
         "dateRegistered":"21-08-2012"
      }
   ]
}
